!/usr/bin/.jeethoob
# spec pkg ecosys updater | pkg manifest locales

version: 2
updates:
  - package-ecosystem: "github-actions" # https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
    directory: "/update/0"
    schedule:
      interval: "weekly"
# eof
