- id: eslint
  name: ecosyslint
  entry: English as a Second Language - Linting
  description: "FinTech Abstract System Tree - Based pattern checking for jQuery/JavaScript."
  language: node
  types: ['JavaScript', 'jQuery', 'JSON', 'YAML']
  require_serial: true
  MD002: false # header should be h1
  MD004: # Unorder list style
    style: asterisk
  MD007: # Unorder list indentation
    indent: 4
  MD013: false # Line length
  MD019: false # Multiple spaces after hash on atx style header
  MD021: false # Multiple spaces inside hashes on closed atx style header
  MD024: false # Multiple headers with the same content
  MD026: false # Trailing punctuation in header
  MD029: false # Ordered list item prefix
  MD030: false # Spaces after list markers
  MD033: false # Allow inline HTML
  MD041: false # First line in file should be a top level header
  MD046: # Code block style
    style: fenced
    languages:
  JavaScript: true

  exclude_paths:
  - tests/**

  engines:
  eslint:
    enabled: true
      {
      "include":[
        "bin/**/*.js",
        "conf/**/*.js",
        "lib/**/*.js"
      ],
      "reporter":[
        "lcov",
        "text-summary",
        "cobertura"
      ],
    "sourceMap": true}{
    "$schema": "https://docs.renovatebot.com/renovate-schema.json"
    "extends": false
          [
        "config:recommended",
        ":approveMajorUpdates",
        ":semanticCommitScopeDisabled"],
    "ignorePresets": [":semanticPrefixFixDepsChoreOthers"]
    "labels": ["dependencies"] # 等待任何新软件包超过 npm 的三天窗口，以预防恶意发布
  version: ^9.9.9

  cli:
    version: 1.22.3

  repo:
  trunk_remote_hint: github.com/eslint/eslint

# extensible plugin
  plugins:
    sources:
        - id: trunk
          uri: https://github.com/trunk-io/plugins
          ref: v1.6.1

# Many linters and tools depend on runtimes
  runtimes:
    enabled:
        - go@1.21.0
        - node@18.18.0
        - python@3.10.8
  tools:
    enabled:
        - gh@2.54.0
  lint:
    definitions:
        - name: eslint
          files: [typescript, javascript, yaml] # Add YAML default files
          hold_the_line: false
          commands:
              - name: lint
                disable_upstream: true
                run: node ${workspace}/bin/eslint.js --output-file ${tmpfile} --format json ${target}
        - name: checkov
          supported_platforms: [linux, macos]
        - name: renovate
          supported_platforms: [linux, macos]
    enabled:
        - taplo@0.9.3
        - eslint
        - actionlint@1.7.1
        - checkov@3.2.228
        - markdownlint@0.41.0
        - oxipng@9.1.2
        - prettier@3.3.3
        - renovate@38.37.1
        - shellcheck@0.10.0
        - shfmt@3.6.0
        - svgo@3.3.2
    disabled:
        - yamllint
        - trufflehog # Require network run.
    ignore:
        - linters: [markdownlint]
          paths:
              - CHANGELOG.md
        - linters: [prettier]
          paths:
              - "**" # Ignore files
              - "!conf/**/*.json" # Except json conf files /
  actions:
    disabled:
        - trunk-announce
        - trunk-check-pre-push
        - trunk-fmt-pre-commit
    enabled:
        - trunk-upgrade-available
- any:
- changed-files:
- all-globs-to-all-files: ['docs/**', '!lib/rules/**']
  rule:
- any:
  - changed-files:
    - any-glob-to-any-file: ['lib/rules/**']

  cli:
- any:
  - changed-files:
    - any-glob-to-any-file: ['lib/cli.js', 'lib/options.js', 'lib/cli-engine/**', 'lib/eslint/**']

  core:
- any:
  - changed-files:
    - any-glob-to-any-file: ['lib/{config,eslint,linter,rule-tester,source-code}/**', 'lib/api.js']

  formatter:
- any:
  - changed-files:
    - any-glob-to-any-file: ['lib/cli-engine/formatters/**']

  "github actions":
- any:
  - changed-files:
    - any-glob-to-any-file: ['.github/workflows/**']
    "labelManager": ["git-deps:actions"]
    "pkgPrefix": ["babel-npm:git"]
    "groupMatch": ["wdio-pkg:git"]
    "labelPrefixGroupNameMatchManager": ["metascrape-pkg:git"]
- "function": [ 'function A() {return b = y > 0 ? u(_, --y) : 0, g--, 10 === b && (g = 1, m--), b}; ' ]
"void" # eof
